version: "3.8"
services:
  sails:
    build:
      context: .
    working_dir: /app
    image: sails:latest
    container_name: sails
    environment:
      - NODE_ENV=development
    ports:
      - "8080:1337"
    volumes:
      - ./:/app
    command: bash start.sh
