version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=resizer
    volumes:
      - ./_docker/mysql:/var/lib/mysql

  sails:
    build:
      context: .
    working_dir: /app
    image: sails:latest
    container_name: sails
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:123@db:3306/resizer
    ports:
      - "8080:1337"
    volumes:
      - ./:/app
    command: bash start.sh
